server:
  port: 8080

spring:
  application:
    name: rabbitmq-demo

  # RabbitMQ配置
  rabbitmq:
    host: 192.168.5.241
    port: 5673
    username: guest
    password: 3sh%2JCtIRHv@95q
    virtual-host: /

    # 连接配置
    connection-timeout: 15000
    publisher-confirm-type: correlated  # 开启发送确认
    publisher-returns: true            # 开启返回确认
    template:
      mandatory: true                 # 强制确认消息路由


# 自定义RabbitMQ队列和交换机配置
rabbitmq:
  queue:
    order.priority: order.priority.tech_share.queue
  exchange:
    order: order.tech_share.exchange



# 日志配置
logging:
  level:
    com.example.rabbitmq.demo: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework.amqp.rabbit: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/rabbitmq-demo.log